# Read the Docs configuration file for Sphinx projects
version: 2

build:
  tools:
    python: "3.12"
# Build documentation in the "docs/" directory with Sphinx
sphinx:
  configuration: docs/config.py

python:
  install:
    - requirements: docs/requirements.txt
